# Generated by Django 5.0.4 on 2024-04-15 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "guest_type",
                    models.CharField(
                        blank=True,
                        choices=[("individual", "개인"), ("corporate", "법인")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("nationality", models.CharField(blank=True, max_length=20, null=True)),
                ("job", models.CharField(blank=True, max_length=50, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                ("visit_count", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
