# Generated by Django 5.0.4 on 2024-04-11 08:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyeongdongReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "building_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("main_building", "본관"),
                            ("new_building", "신관"),
                            ("annex_building", "별관"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("family_suite", "패밀리스위트"),
                            ("8_person_family_suite", "8인 패밀리 스위트"),
                            ("cinema", "씨네마"),
                            ("2_person_spa", "2인스파"),
                            ("4_person_spa", "4인스파"),
                            ("2_person_spa_suite", "2인스파 스위트"),
                            ("4_person_spa_suite", "4인스파 스위트"),
                            ("6_person_spa_suite", "6인스파 스위트"),
                            ("6_person_spa_401", "6인스파 401"),
                            ("6_person_spa_402", "6인스파 402"),
                            ("8th_floor", "8층"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("guest_name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "platform_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("reservation_date", models.DateField(blank=True, null=True)),
                ("lead_time", models.CharField(blank=True, max_length=10, null=True)),
                ("check_in_date", models.DateField(blank=True, null=True)),
                ("check_out_date", models.DateField(blank=True, null=True)),
                ("length_of_stay", models.IntegerField(blank=True, null=True)),
                (
                    "total_room_charge",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("adr", models.DecimalField(decimal_places=0, max_digits=10)),
                ("nationality", models.CharField(blank=True, max_length=20, null=True)),
                ("guest_count", models.IntegerField(blank=True, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=30, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
