# Generated by Django 5.0.4 on 2024-04-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_myeongdong", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myeongdongreservation",
            name="is_checked_in",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checked_in", "투숙"),
                    ("cancel", "취소"),
                    ("before_check_in", "방문전"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="myeongdongreservation",
            name="is_minor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
