# Generated by Django 5.0.4 on 2024-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_myeongdong", "0002_myeongdongreservation_is_checked_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myeongdongreservation",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
