# Generated by Django 5.0.4 on 2024-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_myeongdong", "0003_alter_myeongdongreservation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myeongdongreservation",
            name="total_room_charge",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
